name: learn-github-actions
on: [push]
jobs:
  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-versions: '14'
      - run: npm install -g bats
      - run: bats -v